### ISSUE TITLE
You're putting IM in danger

### ISSUE THREAD

**Issue by mu-hun** [ImagicalCorp/ImagicalMine-Windows#3]
RCON password is set to 'password': 0af529d262e291b51d066af1dbdcdd137a53ee09

How about generating it when installing?

**Comment by mu-hun** [comment]
It's very dangerous for security that set the default rcon password to fixed value "password".

@keithkfng  You don't want to all IM servers to be hacked, right?

I suggest you to set it empty or auto-generate random value when initialization.

**Comment by k3ithos** [comment]
https://github.com/ImagicalCorp/ImagicalMine-Windows/commit/5eec1f74263455ecbed9e27617cc62cc6319b2c0
